# Errors
errors.bad_request=Bad request
errors.method_not_allowed=Method not allowed
errors.unauthorized=Unauthorized

errors.unsupported_media_type=Unsupported media type
errors.service_unavailable=Service unavailable

errors.not_found=Not found
errors.forbidden=Forbidden

errors.internal_server_error=Internal server error
errors.precondition_failed=Precondition failed

errors.too_many_requests=Too many requests
errors.max_accesses=Too many requests
errors.rate_limit_1=You have sent too many requests (1).
errors.rate_limit_2=You have sent too many requests (2).

errors.csrf_failed=CSRF failed
errors.captcha_failed=CAPTCHA failed

errors.field_invalid=The ${0} field is invalid.
errors.field_required=The ${0} field is required.

# Bean Validation
jakarta.validation.constraints.NotNull.message=The ${0} field is invalid.
