config.default_module=default
config.enable_modules=default

config.enable_debug=false
config.enable_session=true
config.enable_json_pretty=true

# View configuration
config.view_dir=/WEB-INF/views
config.view_suffixes=.jsp,.xhtml
config.resource_names=common,messages

# remember_me
remember_me.cookie_name=__remember_me
remember_me.cookie_age=1209600
remember_me.cookie_secure=false
remember_me.cookie_httponly=true
remember_me.cookie_sliding_exp=true

# PrefCookieHandler
com.appslandia.plum.base.PrefCookieHandler.cookie_name=__pref_cookie
com.appslandia.plum.base.PrefCookieHandler.cookie_age=31104000
com.appslandia.plum.base.PrefCookieHandler.cookie_secure=false
com.appslandia.plum.base.PrefCookieHandler.cookie_httponly=true

# Other
config.csp_report_only=false
config.reauth_timeout_sec=600

config.nonce_size=16
config.compress_threshold=4096
